# Generated by Django 3.2.5 on 2021-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0002_album_db_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_db',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/%y', verbose_name=''),
        ),
    ]
