# Generated by Django 3.2.5 on 2021-07-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0003_alter_album_db_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='album_db2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='album/photo/')),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='album_db',
            name='videofile',
        ),
    ]
